version: "3"
services:
  task-lerenew:
    logging: { driver: "awslogs", options: { awslogs-group: "${DOMAIN}", awslogs-stream: "run-task" } }
  task-leissue:
    logging: { driver: "awslogs", options: { awslogs-group: "${DOMAIN}", awslogs-stream: "run-task" } }
  task-openssl:
    logging: { driver: "awslogs", options: { awslogs-group: "${DOMAIN}", awslogs-stream: "run-task" } }
  task-configure:
    logging: { driver: "awslogs", options: { awslogs-group: "${DOMAIN}", awslogs-stream: "run-task" } }
  task-wp:
    logging: { driver: "awslogs", options: { awslogs-group: "${DOMAIN}", awslogs-stream: "run-task" } }
