version: "3"
services:
  cron:
    image: docker:stable
    restart: unless-stopped
    working_dir: $PWD
    command: cron/docker_cmd.sh
    networks:
      - backend
    volumes:
      - ..:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APPROOT=$PWD
      - STAGE
  smtp:
    image: namshi/smtp:latest
    restart: unless-stopped
    hostname: $DOMAIN
    networks:
      - backend
  nginx:
    image: nginx:1.15
    restart: unless-stopped
    command: /docker_cmd.sh
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress:ro
      - ../nginx/nginx.conf.tpl:/etc/nginx/nginx.conf.tpl:ro
      - ../nginx/docker_cmd.sh:/docker_cmd.sh:ro
      - ../var/letsencrypt:/etc/letsencrypt:ro
      - ../var/uploads:/var/www/wordpress-uploads:ro
      - ../var/plugins:/var/www/wordpress-plugins:ro
      - ../var/vhosts:/var/www/vhosts:ro
    environment:
      - DOMAIN
  mysql:
    image: mariadb:10.3
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - mysql:/var/lib/mysql
      - ../mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  php:
    image: wpheadless/wp-php-fpm:7.2.2
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - wordpress:/var/www/wordpress:ro
      - ../var/uploads:/var/www/wordpress-uploads
      - ../var/plugins:/var/www/wordpress-plugins:ro
networks:
  frontend:
