version: "3"
services:
  x-task-certbot: &task-certbot
    image: certbot/certbot:latest
    entrypoint: []
    working_dir: $PWD
    volumes:
      - ../tasks:${PWD}/tasks:ro
      - ../var/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN
      - ADMIN_EMAIL
      - STAGE
  task-lerenew:
    <<: *task-certbot
    volumes:
      - ../tasks:${PWD}/tasks:ro
      - ../var/letsencrypt:/etc/letsencrypt
      - ../var/vhosts:/var/www/vhosts
  task-leissue:
    <<: *task-certbot
    ports:
      - 80:80
      - 443:443
  task-openssl:
    <<: *task-certbot
    command: sh
  task-configure:
    <<: *task-certbot
    command: sh
    volumes:
      - ..:/$PWD
  task-wp:
    image: wordpress:cli-2-php7.4
    entrypoint: []
    working_dir: $PWD
    user: root
    networks:
      - backend
    volumes:
      - wordpress:/var/www/wordpress
      - ..:/$PWD
      - ../var/uploads:/var/www/wordpress-uploads
      - ../var/plugins:/var/www/wordpress-plugins
      - ../wordpress/mu-plugins:/var/www/wordpress-mu-plugins
    environment:
      - APPROOT=$PWD
      - SMTPHOST=smtp
      - DB_HOST=mysql
      - STAGE
      - DOMAIN
      - ADMIN_EMAIL
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AUTH_KEY
      - SECURE_AUTH_KEY
      - LOGGED_IN_KEY
      - NONCE_KEY
      - AUTH_SALT
      - SECURE_AUTH_SALT
      - LOGGED_IN_SALT
      - NONCE_SALT
      - WORDPRESS_VERSION=5.3.2
      - WORDPRESS_TITLE=WpHeadless
      - ACF_PRO_VERSION=5.8.4
      - WORDPRESS_PLUGINS=
          custom-post-type-ui=1.7.1
          acf-to-rest-api=3.1.0
          amazon-s3-and-cloudfront=2.3.2
          wordpress-importer=0.6.4
          title-and-nofollow-for-links=1.07
          disable-comments=1.10.2
